### ISSUE TITLE
like button not working

### ISSUE THREAD

**Issue by mberatsanli** [JijaProGamer/youtube-selfbot-api#4]
like() method not working on my side pupetter couldn't find the like button in the dom. 

### Solution
It looks like `yt-smartimation` added by the yt devs.

```js
document.querySelector(`ytd-menu-renderer.ytd-watch-metadata > div:nth-child(1) > ytd-segmented-like-dislike-button-renderer:nth-child(1) > yt-smartimation > div ytd-toggle-button-renderer:nth-child(1) > yt-button-shape:nth-child(1) > button:nth-child(1)`)
```

<img width="1053" alt="Screenshot 2023-05-25 at 22 11 58" src="https://github.com/JijaProGamer/youtube-selfbot-api/assets/15654470/2e620a5a-d4ed-4bd9-9342-1bd853c30921">

**Comment by JijaProGamer** [comment]
Ill fix the like selector in the next update

**Comment by JijaProGamer** [comment]
I've fixed this in the latest update.
